sudo: required
dist: trusty
group: beta
language: java
jdk:
  - oraclejdk8
addons:
  apt:
    packages:
      - rpm
cache:
  directories:
    - $HOME/.m2
services:
  - docker
script:
  - mvn test verify -Dmaven.javadoc.skip=true -B -V
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpm && export RELEASE_RPM_FILE=$(find target/ -name '*.rpm' | tail -1)
  - rm -f target/original-*.jar
  - export RELEASE_PKG_FILE=$(ls target/*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: X/71JGGY3C9mbR9odUpTLdiz7o9JEe70DBwid+UlUuHK+B145yOSCI/ODdwkQFrxbJ7O+xcUe6Rm8cPGCaUtS8TYN67WuDuXxpEXPX5U1LkEwCzl6cB/eV3OOkiMIB+5k66TR9S3mNKDgd3/WIZvkWfu6CIoL3k9KcybEFWQRkA=
  file: 
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk8
