language: java
jdk:
  - oraclejdk7
  - oraclejdk8
before_deploy:
  - mvn jdeb:jdeb && export RELEASE_DEB_FILE=$(ls target/*.deb)
  - mvn rpm:rpmb && export RELEASE_RPM_FILE=$(ls target/*.rpm)
  - export RELEASE_PKG_FILE=$(ls target/graylog-alarmcallback-rundeck-*.jar)
  - echo "Deploying release to GitHub releases"
deploy:
  provider: releases
  api_key:
    secure: "I6gB/OSr/KNulUna2JKUkqvPZWvqq0RlMAbYXu85E2w81u5WkRnkV3J9QXPkp6mdOaupsvBuuafzpWuMtOwaOgTxI6v3CYfMcIAyNuZNqbr2h0SnS3ywIbp+vhrthbK/CWXUVl1g46uvm2wgTY8NPEywTKiKba/hsWtuTpOPRvo="
  file: 
    - "${RELEASE_PKG_FILE}"
    - "${RELEASE_DEB_FILE}"
    - "${RELEASE_RPM_FILE}"
  skip_cleanup: true
  on:
    tags: true
    jdk: oraclejdk7
